
package net.eads.astrium.hmas.exceptions;

import javax.xml.ws.WebFault;
import net.opengis.ows.x11.ExceptionDocument;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-06T10:49:28.625+01:00
 * Generated source version: 2.6.1
 */

public class DescribeSensorFault extends DreamEoSpsException {
    
    public DescribeSensorFault() {
        super();
    }
    
    public DescribeSensorFault(String message) {
        super(message);
        
        exception = ExceptionDocument.Factory.newInstance();
        exception.addNewException().addExceptionText(message);
    }
    
    public DescribeSensorFault(String message, Throwable cause) {
        super(message, cause);
        exception.addNewException().addExceptionText(message);
    }

    public DescribeSensorFault(String message, net.opengis.ows.x11.ExceptionDocument exception) {
        super(message);
        this.exception = exception;
    }

    public DescribeSensorFault(String message, net.opengis.ows.x11.ExceptionDocument exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public net.opengis.ows.x11.ExceptionDocument getFaultInfo() {
        return this.exception;
    }
}
