
package net.eads.astrium.hmas.exceptions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-06T10:49:28.656+01:00
 * Generated source version: 2.6.1
 */

public class GetCapabilitiesFault extends DreamEoSpsException {
    
    public GetCapabilitiesFault() {
        super();
    }
    
    public GetCapabilitiesFault(String message) {
        super(message);
    }
    
    public GetCapabilitiesFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCapabilitiesFault(String message, net.opengis.ows.x11.ExceptionDocument exception) {
        super(message);
        this.exception = exception;
    }

    public GetCapabilitiesFault(String message, net.opengis.ows.x11.ExceptionDocument exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public net.opengis.ows.x11.ExceptionDocument getFaultInfo() {
        return this.exception;
    }
}
